$script = <<-SCRIPT
echo "192.168.56.11   devsecops" >> /etc/hosts

# Installing pre-requisite software
apt update
apt install -y docker.io docker-compose git ripgrep pip python3

# Setting up Java and Maven, for Selenium
apt install -y openjdk-17-jdk
cd ~
wget https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
cd /opt
tar zxvf ~/apache-maven-3.8.8-bin.tar.gz
ln -s apache-maven-3.8.8 /opt/maven
cd ~; rm apache-maven*.tar.gz

echo 'export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64/"' > /etc/profile.d/maven.sh
echo 'export M2_HOME="/opt/maven"' >> /etc/profile.d/maven.sh
echo 'export MAVEN_HOME="/opt/maven"' >> /etc/profile.d/maven.sh
echo 'export PATH="${M2_HOME}/bin:${PATH}"' >> /etc/profile.d/maven.sh

chmod +x /etc/profile.d/maven.sh

# Installing NodeJS from outside sources.
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
apt update
apt install -y nodejs      # Fetching NodeJS 16 from NodeSource

echo "NODE INSTALLED: $(node --version)"

# Installing alternative and faster NodeJS package manager
npm install -g pnpm

# Installing Angular
npm install --location=global @angular/cli@latest

# Installing Chromium, for headless testing.
apt install -y chromium-browser 
echo "export CHROME_BIN=\"/snap/bin/chromium\"" >> /etc/bash.bashrc
echo "export CHROME_BIN=\"/snap/bin/chromium\"" >> /etc/profile

# Installing Azure CLI
apt install -y ca-certificates curl apt-transport-https lsb-release gnupg

curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

export AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    tee /etc/apt/sources.list.d/azure-cli.list

apt update
apt install -y azure-cli

# Setting up and starting Docker.
usermod -a -G docker vagrant
systemctl enable docker
systemctl start docker
docker pull hello-world

# Pulling images needed for Selenium labs
docker pull selenium/node-chrome
docker pull selenium/node-edge
docker pull selenium/node-firefox
docker pull selenium/hub
docker pull bkimminich/juice-shop

# Pulling image for SCA with OSV Scanner
docker pull ghcr.io/google/osv-scanner:latest

# Pulling Nessus image for day 5
docker pull tenableofficial/nessus


SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define :devsecops do |devsecops|
    devsecops.vm.hostname = "devsecops"
    #devsecops.vm.box = "bento/ubuntu-20.04"    # This was the original
    devsecops.vm.box = "bento/ubuntu-22.04"

    # Switch these two, if VirtualBox complains about "permission denied" on networking.
    devsecops.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: "dsonet"
    #devsecops.vm.network "private_network", ip: "192.168.56.11"
    ###

    devsecops.vm.network "forwarded_port", guest: 3000, host: 3000
    devsecops.vm.network "forwarded_port", guest: 4444, host: 4444
    devsecops.vm.network "forwarded_port", guest: 8834, host: 8834

    if Vagrant.has_plugin?("vagrant-vbguest")
      devsecops.vbguest.auto_update = false
    end

    devsecops.vm.provider "virtualbox" do |v|
      v.memory = 4096          # Change to 8192 if possible
      v.cpus = 4               # Change to 6 if possible
    end
    devsecops.vm.provision "setup", type: "shell", inline: $script
  end

end
