version: '3.1'

services:

  nessus:
    image: tenable/nessus
    restart: always
    container_name: nessus
    environment:
      USERNAME: tess
      PASSWORD: secret123
      ACTIVATION_CODE: 
    ports:
      - 8834:8834
