variables:
  # Used for container names and for webapp URLs
  - name: 'team'
    value: 'team1'
  # DO NOT CHANGE THE FOLLOWING VARIABLES.
  # ONLY CHANGE YOUR TEAM NAME, ABOVE HERE...
  # Used to refer to AzDO service connection and to actual registry.
  - name: 'registry'
    value: 'unixeriusdso'
  # Used for the WebApp Service
  - name: 'webapp'
    value: 'unixeriusdso-${{ variables.team }}'
  # Used to deploy resources to Azure
  - name: 'azuresub'
    value: 'Azure Unixerius Learning'
  # Should be re-defined in the DTAP phases / stages
  - name: 'dtap'
    value: 'dev'

trigger:
  - manual
    
pool:
  vmImage: ubuntu-latest


stages:
- stage: test_application
  condition: always()

  jobs:
  - job: run_cypress
    steps:
    - task: Bash@3
      displayName: install_npm_dependencies
      inputs:
        targetType: 'inline'
        script: |
          npm install
    - task: Bash@3
      displayName: run_and_test_juiceshop
      inputs:
        targetType: 'inline'
        script: |
          npm start &
          sleep 5
          npx cypress run --config video=true
    - task: PublishBuildArtifacts@1
      displayName: publish_cypress_evidence
      inputs:
        PathtoPublish: 'cypress/videos/e2e/login.spec.ts.mp4'
        artifact: login.spec.ts.mp4
    - task: PublishBuildArtifacts@1
      displayName: publish_cypress_evidence
      inputs:
        PathtoPublish: 'cypress/screenshots/'
        artifact: screenshots

- stage: build_package
  dependsOn:
  - test_application
  condition: always()
  jobs:
  - job: build_and_push_image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: ${{ variables.registry }}
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: ${{ variables.registry }}
        repository: ${{ variables.team }}
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: ${{ variables.dtap }}
    - task: Docker@2
      inputs:
        containerRegistry: ${{ variables.registry }}
        command: 'logout'

- stage: run_webapp
  dependsOn:
  - test_application
  - build_package
  condition: always()
  
  jobs:
  - job: update_appsvc_dev
    steps:
    - task: AzureWebAppContainer@1
      displayName: update_webapp
      inputs:
        azureSubscription: ${{ variables.azuresub }}
        appName: ${{ variables.webapp }}
        containers: '${{ variables.registry }}.azurecr.io/${{ variables.team }}:${{ variables.dtap }}'
        appSettings: '-Port 3000 -WEBSITES_PORT 3000'
        configurationStrings: '-acrUseManagedIdentityCreds true'
    
    # Sleeping for five minutes. I have seen the restart take 10-12 minutes.
    - task: Bash@3
      displayName: sleep_and_wait
      inputs:
        targetType: 'inline'
        script: 'sleep 300'
